### ISSUE TITLE
[39232] Failed to execute script 'PBLMM' due to unhandled exception!

### ISSUE THREAD

**Issue by science64** [klannk/Peptide_based_LMM#1]
Hello Kevin,

I have tested the latest version "exe" file and when I click to run and I got this error, I am not sure what is the issue here. Thanks in advance.

```
Traceback (most recent call last):
  File "PBLMM.py", line 262, in <module>
  File "PBLMM.py", line 193, in main
IndexError: list index out of range
[39232] Failed to execute script 'PBLMM' due to unhandled exception!
```

Best

**Comment by enthus1ast** [comment]
@science64 193 is:

`    settings_path = sys.argv[1] `

I think you have started the wrong executable.

**Comment by science64** [comment]
> 


Hey David thanks, I have used in the dist folder named as 'PBLMM.exe' executable from this link https://github.com/klannk/Peptide_based_LMM/blob/master/dist/PBLMM.exe, is there any other one? thanks

**Comment by enthus1ast** [comment]
There is this PBLMM.exe which is the application that is called by the gui, this tool gets the config (that is also written by the gui) then there is the gui, which seems to be electron, i current don't know where this gets installed.
